export enum FileResourceEnum {
  VENDOR = 'vendor',
  MANDI = 'mandi',
  USER = 'user',
  DELIVERY_PARTNER = 'delivery-partner',
  CATEGORY = 'category',
  SOCIETY = 'society',
  INSTITUTION = 'institution',
  PRODUCT = 'product',
  AUDIT = 'audit',
  DOCUMENT = 'document',
  OTHER = 'other',
  VENDOR_INVOICE = 'vendor-invoice',
  FRANCHISE = 'franchise',
  B2B = 'b2b',
  CONSIGNMENT = 'consignment',
  PUTAWAY_MANAGEMENT = 'putaway-management',
  ORDER_PACKING = 'order-packing',
}
